---
title: "Mika Leslie"
---

##### Email: mika.leslie8@gmail.com
****

## Highlights of Qualifications

- **Collaboration** - Worked in many professional environments where collaboration was essential, including a 24 person Orientation Staff in 2019 
- **Communication** - Extensive experience from jobs and team sports in effectively communicating with a wide range of people
- **Leadership** - Responsible for leading groups of students through Orientation at UCSB; experience helping new members of teams acclimate 
- **Efficient Multitasker** - Able to effectively meet customer needs in fast-paced and complex environments
- **Excellent Work Ethic** - Maintained a GPA above 3.7 throughout college on top of several extra-curricular activities

***

## Technical Skills
- **Languages** - R, STATA
- **Development** - Markdown, GitHub, MS Office, Google Suite
- **Mapping** - <code>sf</code>, <code>raster</code>, <code>leaflet</code>, <code>OpenStreetMap</code>, <code>whitebox</code>    

***** 

## Experience

#### Administrative Student Assistant | UCSB Chemsitry Department | **Oct 2019 - Present**
- Advised students on relevant academic information
- Answered emails and phone calls for the advising team
- Assisted with any required administration tasks, including data entry, excel work, and updating the department website

#### UCSB Orientation Staff | UCSB Orientation Programs | **Apr 2019 - Aug 2019**
- Received over 100 hours of training on UCSB academic requirements, campus resources, and how to advise students and facilitate workshops
- Led groups of 12-14 students through an immersive two day program, often working over 12 hours a day
- Led tours and panel discussions in front of 50-100 people
- Worked collaboratively on a team with 23 other UCSB students to keep the program running smoothly

#### Social Media/Outreach Coordinator | UCSB Women's Ultimate Frisbee | **Jan 2018 - Present**
- Over the past two years, revived the social media presence of UCSB's Women's Club Ultimate Frisbee Team, increasing the following by tenfold
- Engage with stakeholders across platforms and increased community engagement
- Ran a fundraising campaign that completely funded the costs of attending nationals for the entire team in 2018

#### Floor Staff/Barista | Stirato Bakery and Cafe | **June 2018 - September 2018**
- Worked full time in a busy cafe as a waitress and barista
- Able to work efficiently in a fast-paced environment

****
## Education

#### University of California Santa Barbara | **Expected June 2021**
- B.S. in Environmental Studies
- Current GPA: 3.89
- Dean's List: Fall 2017, Winter 2018, Spring 2018, Winter 2019, Fall 2019, Winter 2020, Spring 2020
